{{- range .Values.kartons }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .name }}
  name: {{ .name }}
spec:
  replicas: {{ default 1 .replicas | int }}
  selector:
    matchLabels:
      io.kompose.service: {{ .name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .name }}
    spec:
      containers:
        - image: {{ .image }}:{{ .imageTag }}
          name: {{ .name }}
          resources: {}
          envFrom:
            - configMapRef: 
                name: karton-config
            - secretRef:
                name: karton-secrets
      restartPolicy: Always
status: {}
---
{{- end -}}