# Karton Configuration
# For each object in the karton's list we'll generate a karton deployment
# Note there is no matching service since they consume messages from a redis
# Queue and aren't responsible for reaching out to the 

# Shared karton configuration is under /clusters/dev/mwdb/config
# Configuration is mapped in as environment variables

kartons:
  - name: "karton-yaramatcher"
    image: "ghcr.io/jconnor0426/karton-yaramatcher"
    imageTag: "0b3e450"
    replicas: 1
  - name: "karton-classifier"
    image: "certpl/karton-classifier"
    imageTag: "84c642c666334db3df66b98752784c2044aa3c2d"
    replicas: 1
  - name: "karton-mwdb-reporter"
    image: "certpl/karton-mwdb-reporter"
    imageTag: "f4729b0b7a099f7d97ce1d4b52adeece4705bf62"
    replicas: 1