apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: karton-system
  name: karton-system
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: karton-system
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: karton-system
    spec:
      containers:
        - args:
            - --setup-bucket
          command:
            - karton-system
          image: certpl/karton-system:7ef22b7906a4d50cd73c024da0d7acba76218734
          name: karton-system
          resources: {}
          envFrom:
            - configMapRef: 
                name: karton-config
            - secretRef:
                name: karton-secrets
      restartPolicy: Always
status: {}
