apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: karton-mwdb-reporter
  name: karton-mwdb-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: karton-mwdb-reporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: karton-mwdb-reporter
    spec:
      containers:
        - image: certpl/karton-mwdb-reporter:1afa32251b4826eac4386596b4a20f295699faec
          name: karton-mwdb-reporter
          resources: {}
          envFrom:
            - configMapRef: 
                name: karton-config
            - secretRef:
                name: karton-secrets
      restartPolicy: Always
status: {}
