apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mwdb
  name: mwdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mwdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mwdb
    spec:
      containers:
        - env:
            - name: MWDB_REDIS_URI
              value: redis://redis/
            - name: UWSGI_PROCESSES
              value: "4"
          envFrom:
            - configMapRef: 
                name: mwdb-config
            - secretRef:
                name: mwdb-secrets
          image: ghcr.io/jconnor0426/mwdb:main
          name: mwdb
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
