apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mwdb
  name: mwdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mwdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mwdb
    spec:
      containers:
        - envFrom:
            - configMapRef: 
                name: mwdb-config
            - secretRef:
                name: mwdb-secrets
            - configMapRef: 
                name: karton-config
            - secretRef:
                name: karton-secrets
          image: ghcr.io/jconnor0426/mwdb:e0138fb
          name: mwdb
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
